=== chouyi/cuplv.github.io/cvx.xsd
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!-- Derived using MOSO Xmplify 1.2.2 by Evan Chang on 2013-02-24 04:50:21 +0000 -->
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' elementFormDefault='qualified'>
    <xs:element name='cv'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='news-list'/>
                <xs:element ref='projects'/>
                <xs:element ref='publications'/>
                <xs:element ref='persons'/>
                <xs:element ref='events'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='news-list'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='news'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='news'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='news-snippet'/>
                <xs:element minOccurs='0' ref='news-detail'/>
                <xs:choice>
                    <xs:element ref='news-page'/>
                    <xs:element minOccurs='0' maxOccurs='unbounded' ref='talk-announcement'/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name='date' use='required'/>
            <xs:attribute name='id' use='required'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='news-snippet'>
        <xs:complexType mixed='true'>
            <xs:choice maxOccurs='unbounded'>
                <xs:element ref='a'/>
                <xs:element ref='ref'/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name='news-detail'>
        <xs:complexType mixed='true'>
            <xs:choice maxOccurs='unbounded'>
                <xs:element ref='a'/>
                <xs:element ref='ref'/>
                <xs:element ref='div'/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name='div'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='ref'/>
            </xs:sequence>
            <xs:attribute name='class' use='required'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='news-page'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='p'/>
            </xs:sequence>
            <xs:attribute name='header' use='required'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='talk-announcement'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='speaker'/>
                <xs:element ref='affiliation'/>
                <xs:element ref='when'/>
                <xs:element ref='where'/>
                <xs:element ref='title'/>
                <xs:element minOccurs='0' ref='host'/>
                <xs:element ref='abstract'/>
                <xs:element minOccurs='0' ref='bio'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='speaker'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='ref'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='affiliation' type='xs:string'/>
    <xs:element name='when' type='xs:string'/>
    <xs:element name='where' type='xs:string'/>
    <xs:element name='host'>
        <xs:complexType>
            <xs:attribute name='person' use='required'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='bio'>
        <xs:complexType mixed='true'>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='p'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='projects'>
        <xs:complexType/>
    </xs:element>
    <xs:element name='publications'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='pub'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='pub'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='title'/>
                <xs:element ref='authors'/>
                <xs:element ref='urls'/>
                <xs:element ref='howpub'/>
                <xs:element minOccurs='0' ref='note'/>
                <xs:element minOccurs='0' ref='abstract'/>
            </xs:sequence>
            <xs:attribute name='id' use='required'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='authors'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='author'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='author'>
        <xs:complexType>
            <xs:attribute name='person' use='required'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='urls'>
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs='0' maxOccurs='unbounded' ref='url'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='howpub'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='proceedings'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='proceedings'>
        <xs:complexType>
            <xs:attribute name='event' use='required'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='note'>
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs='0' ref='tr'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='tr'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='extendedtr'/>
                <xs:element ref='number'/>
                <xs:element ref='url'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='extendedtr'>
        <xs:complexType/>
    </xs:element>
    <xs:element name='number' type='xs:string'/>
    <xs:element name='persons'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='person'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='person'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='name'/>
                <xs:choice minOccurs='0' maxOccurs='unbounded'>
                    <xs:element ref='url'/>
                    <xs:element ref='face'/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name='group'/>
            <xs:attribute name='id' use='required'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='face' type='xs:string'/>
    <xs:element name='events'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='series'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='series'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='name'/>
                <xs:choice minOccurs='0'>
                    <xs:element ref='abbrev'/>
                    <xs:element ref='longPrefix'/>
                </xs:choice>
                <xs:element maxOccurs='unbounded' ref='event'/>
            </xs:sequence>
            <xs:attribute name='id' use='required'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='abbrev' type='xs:string'/>
    <xs:element name='longPrefix' type='xs:string'/>
    <xs:element name='event'>
        <xs:complexType>
            <xs:choice maxOccurs='unbounded'>
                <xs:element ref='url'/>
                <xs:element ref='date'/>
                <xs:element ref='location'/>
                <xs:element ref='nth'/>
            </xs:choice>
            <xs:attribute name='id' use='required'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='date' type='xs:string'/>
    <xs:element name='location' type='xs:string'/>
    <xs:element name='nth' type='xs:string'/>
    <xs:element name='ref'>
        <xs:complexType>
            <xs:attribute name='key' use='required'/>
            <xs:attribute name='mode'/>
            <xs:attribute name='table' use='required'/>
            <xs:attribute name='text'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='a'>
        <xs:complexType mixed='true'>
            <xs:attribute name='href' use='required'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='title' type='xs:string'/>
    <xs:element name='abstract'>
        <xs:complexType mixed='true'>
            <xs:choice maxOccurs='unbounded'>
                <xs:element ref='p'/>
                <xs:element ref='ul'/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name='ul'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='li'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='li' type='xs:string'/>
    <xs:element name='p'>
        <xs:complexType mixed='true'>
            <xs:choice maxOccurs='unbounded'>
                <xs:element ref='a'/>
                <xs:element ref='ref'/>
                <xs:element ref='em'/>
                <xs:element ref='fmt'/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name='em' type='xs:string'/>
    <xs:element name='fmt'>
        <xs:complexType mixed='true'>
            <xs:attribute name='kind' use='required'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='url'>
        <xs:complexType mixed='true'>
            <xs:attribute name='name'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='name' type='xs:string'/>
</xs:schema>

=== chouyi/cuplv.github.io/pl.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE cv [
<!ENTITY emdash "&#8212;">
]>

<cv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cvx/cvx.xsd">
  <news-list>
    <news date="2014.02.19" id="phdvisit-2014">
      <news-snippet>
	Prospective Ph.D. students visit February 21. Welcome!
      </news-snippet>
    </news>
    <news date="2014.02.03" id="blackshear-facebook14">
      <news-snippet>
	<ref table="person" key="blackshear"/> wins a
	<a href="https://www.facebook.com/notes/facebook-fellowship-program/announcing-the-facebook-graduate-fellowship-2014-2015-winners/1516002375292350">Facebook Graduate Fellowship</a>!
      </news-snippet>
      <news-detail>
	<ref table="person" key="blackshear"/> is one of only eleven winners of a
	<a href="https://www.facebook.com/notes/facebook-fellowship-program/announcing-the-facebook-graduate-fellowship-2014-2015-winners/1516002375292350">2014-2015 Facebook Graduate Fellowship</a>!
      </news-detail>
    </news>
    <news date="2013.10.01" id="papers-popl14">
      <news-snippet>
	Two papers with CUPLV authors accepted to <ref table="event" key="popl14"/>!
	[<ref table="pub" key="fissile-popl14" text="1"/>,
	 <ref table="pub" key="acceleration-popl14" text="2"/>]
      </news-snippet>
      <news-detail>
	CUPLV authors <ref table="person" key="coughlin"/>, <ref table="person" key="bec"/>, and <ref table="person" key="srirams"/>
	with collaborators 
	have had papers accepted for presentation at <ref
	table="event" key="popl14"/> in January (<ref table="pub"
	key="fissile-popl14" mode="authors"/>
	and <ref table="pub" key="acceleration-popl14" mode="authors"/>).
      </news-detail>
    </news>
    <news date="2013.06.08" id="cuplv-summer13">
      <news-snippet>
	Check out CUPLV at
	<ref table="event" key="pldi13"/>,
	<ref table="event" key="lics13"/>,
	<ref table="event" key="ecoop13"/>, and
	<ref table="event" key="cav13"/> this summer.
      </news-snippet>
      <news-detail>
	<float>
	  <ref table="person" key="blackshear" mode="medium-face"/>
	  <ref table="person" key="cox" mode="medium-face"/>
	  <ref table="person" key="chakarov" mode="medium-face"/>
	  <ref table="person" key="bec" mode="medium-face"/>
	  <ref table="person" key="srirams" mode="medium-face"/>
	  <ref table="person" key="cernyp" mode="medium-face"/>
	</float>
	Eight CUPLV papers are being presented this summer:
	<ref table="event" key="pldi13"/> June 16-22
	[<ref table="pub" key="thresher-pldi13" mode="authors"/>,
	<ref table="pub" key="probabilistic-pldi13" mode="authors"/>,
	<ref table="pub" key="acspec-pldi13" mode="authors"/>],
	<ref table="event" key="lics13"/> June 25-28
	[<ref table="pub" key="automata-lics13" mode="authors"/>],
	<ref table="event" key="ecoop13"/> July 1-5
	[<ref table="pub" key="quicgraphs-ecoop13" mode="authors"/>], and
	<ref table="event" key="cav13"/> July 13-19
	[<ref table="pub" key="concursyn-cav13" mode="authors"/>,
	<ref table="pub" key="martingales-cav13" mode="authors"/>,
	<ref table="pub" key="flowstar-cav13" mode="authors"/>].
      </news-detail>
    </news>
    <news date="2013.05.21" id="cox-chateaubriand13">
      <news-snippet>
	<ref table="person" key="cox"/> wins a
	<a href="http://france-science.org/Chateaubriand-Fellowship-2013.html">Chateaubriand Fellowship</a>!
      </news-snippet>
      <news-detail>
	<ref table="person" key="cox"/> wins a
	<a href="http://france-science.org/Chateaubriand-Fellowship-2013.html">Chateaubriand Fellowship</a>
	in Science, Technology, Engineering, and Mathematics
	from the Embassy of France in the United States to study and conduct research in France.
      </news-detail>
    </news>
    <news date="2013.05.07" id="artifact-ecoop13">
      <news-snippet>
	<ref table="pub" key="quicgraphs-ecoop13" mode="authors"/> wins <ref table="event" key="ecoop13"/> distinguished artifact award!
      </news-snippet>
      <news-detail>
	<float>
  	  <ref table="person" key="cox" mode="medium-face"/>
	  <ref table="person" key="bec" mode="medium-face"/>
	  <ref table="person" key="srirams" mode="medium-face"/>
	</float>
	The artifact supplementing "<ref table="pub" key="quicgraphs-ecoop13"/>" has been
	<a href="http://www.lirmm.fr/ecoop13/index.php/validated-artifacts">validated</a>
	and has received the distinguished artifact award at <ref table="event" key="ecoop13"/>!
      </news-detail>
    </news>
    <news date="2013.03.25" id="cox-facebook13">
      <news-snippet>
	<ref table="person" key="cox"/> named a <a href="https://www.facebook.com/notes/facebook-academics/announcing-the-2013-2014-facebook-graduate-fellows/514353405282738">2013-2014 Facebook Graduate Fellowship Finalist</a>.
      </news-snippet>
    </news>
    <news date="2013.03.06" id="papers-cav13">
      <news-snippet>
	Three papers with CUPLV authors accepted to <ref table="event" key="cav13"/>!
	[<ref table="pub" key="concursyn-cav13" text="1"/>,
	 <ref table="pub" key="martingales-cav13" text="2"/>,
	 <ref table="pub" key="flowstar-cav13" text="3"/>]
      </news-snippet>
      <news-detail>
	CUPLV authors <ref table="person" key="cernyp"/>, <ref table="person" key="chakarov"/>, and <ref table="person" key="srirams"/>
	with collaborators 
	have had papers accepted for presentation at <ref
	table="event" key="cav13"/> in July (<ref table="pub"
	key="concursyn-cav13" mode="authors"/>, <ref
	table="pub" key="martingales-cav13" mode="authors"/>,
	and <ref table="pub" key="flowstar-cav13" mode="authors"/>).
      </news-detail>
    </news>
    <news date="2012.03.04" id="paper-ecoop13">
      <news-snippet>
	Paper by <ref table="pub" key="quicgraphs-ecoop13" mode="authors"/>
	accepted to <ref table="event" key="ecoop13"/>.
      </news-snippet>
      <news-detail>
	CUPLV authors <ref table="person" key="cox"/>, <ref table="person" key="bec"/>, and <ref table="person" key="srirams"/>
	have had a paper "<ref table="pub" key="quicgraphs-ecoop13"/>"
	accepted for presentation at <ref table="event" key="ecoop13"/> in July.
      </news-detail>
    </news>
    <news date="2013.03.04" id="tapascfp-2013">
      <news-snippet>
	Submit Analyzer Pearls to <ref table="event" key="tapas13" />!
      </news-snippet>
    </news>
    <news date="2013.02.21" id="phdvisit-2013">
      <news-snippet>
	Prospective Ph.D. students visit February 22. Welcome!
      </news-snippet>
    </news>
    <news date="2013.02.04" id="papers-pldi13">
      <news-snippet>
	Great showing for CUPLV authors at <ref table="event" key="pldi13"/>: 3 papers accepted! [<ref table="pub" key="thresher-pldi13" text="1"/>, <ref table="pub" key="probabilistic-pldi13" text="2"/>, <ref table="pub" key="acspec-pldi13" text="3"/>]
      </news-snippet>
      <news-detail>
	<float>
	  <ref table="person" key="blackshear" mode="medium-face"/>
	  <ref table="person" key="bec" mode="medium-face"/>
	  <ref table="person" key="srirams" mode="medium-face"/>
	  <ref table="person" key="chakarov" mode="medium-face"/>
	</float>
	CUPLV authors <ref table="person" key="blackshear"/>, <ref table="person" key="bec"/>, <ref table="person" key="srirams"/>, and <ref table="person" key="chakarov"/>
	with collaborators <ref table="person" key="msridhar"/>,
	<ref table="person" key="sumitg"/>, and
	<ref table="person" key="slahiri"/>
	have had papers accepted for presentation at <ref
	table="event" key="pldi13"/> in June (<ref table="pub"
	key="thresher-pldi13" mode="authors"/>, <ref
	table="pub" key="probabilistic-pldi13" mode="authors" />,
	and <ref table="pub" key="acspec-pldi13"
	mode="authors" />).
      </news-detail>
    </news>
    <news date="2013.01.31" id="sigcse2013src">
      <news-snippet>
	Poster accepted to <ref table="event" key="sigcse2013"/>
	Student Research Competition
	(by <ref table="person" key="lapinski"/> et al.).
      </news-snippet>
      <news-detail>
	<ref table="person" key="lapinski"/> and
	<ref table="person" key="srirams" />
	have had their poster accepted to the
	 <ref table="event" key="sigcse2013"/>
	Student Research Competition.
      </news-detail>
    </news>
    <news date="2013.01.31" id="icse2013nier">
      <news-snippet>
	Paper accepted to <ref table="event" key="icse13"/> (New and
	Emerging Results Track) (by <ref table="pub" key="ui-icse-nier13" mode="authors"/>).
      </news-snippet>
      <news-detail>
	<ref table="person" key="givens"/>,
	<ref table="person" key="chakarov"/>,
	<ref table="person" key="srirams"/>, and
	<ref table="person" key="yeh" />
	have had their paper accepted for presentation
	at <ref table="event" key="icse13"/>
	(New and Emerging Results Track) in May.
    </news-detail>
    </news>
    <news date="2013.01.23" id="jha-colloquium-2013">
      <news-snippet>
	<ref table="person" key="sumitjha"/> visits January 24.
      </news-snippet>
      <news-detail>
	<ref table="person" key="sumitjha"/> from University of Central Florida is visiting us
	on January 24, 2013. He is giving a Computer Science
	Colloquium entitled
	"Validation and Parameter Discovery for Stochastic Computational Models from Behavioral Specifications"
	at 3:30pm in ECCR
	265 on Thursday, January 24, 2013.
      </news-detail>
      <talk-announcement>
	<speaker><ref table="person" key="sumitjha"/></speaker>
	<affiliation>University of Central Florida</affiliation>
	<when>01-24-2013 15:30</when>
	<where>ECCR 265</where>
	<title>
	  Validation and Parameter Discovery for Stochastic Computational Models from Behavioral Specifications
	</title>
	<abstract>
